export const userData = [
    {
      id: 1,
      name: 'Alice Johnson',
      country: 'United States',
      status: 'Active',
      dateOfBirth: '1990-05-15',
      email: 'alice.johnson@example.com',
      phone: '+1-202-555-0143',
      profilePicture: 'https://example.com/images/alice.jpg',
    },
    {
      id: 2,
      name: 'Carlos Ramirez',
      country: 'Mexico',
      status: 'Inactive',
      dateOfBirth: '1985-12-10',
      email: 'carlos.ramirez@example.com',
      phone: '+52-55-1234-5678',
      profilePicture: 'https://example.com/images/carlos.jpg',
    },
    {
      id: 3,
      name: 'Lina Wang',
      country: 'China',
      status: 'Active',
      dateOfBirth: '1992-03-25',
      email: 'lina.wang@example.com',
      phone: '+86-21-9876-5432',
      profilePicture: 'https://example.com/images/lina.jpg',
    },
    {
      id: 4,
      name: 'John Smith',
      country: 'Canada',
      status: 'Pending',
      dateOfBirth: '1988-07-22',
      email: 'john.smith@example.com',
      phone: '+1-416-555-0123',
      profilePicture: 'https://example.com/images/john.jpg',
    },
    {
      id: 5,
      name: 'Fatima El-Khoury',
      country: 'Lebanon',
      status: 'Active',
      dateOfBirth: '1995-01-30',
      email: 'fatima.elkhoury@example.com',
      phone: '+961-1-234567',
      profilePicture: 'https://example.com/images/fatima.jpg',
    },
  ];
  